### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/work#2]
# TODO
- [ ] service is on production
- [ ] integrate `ats`
- `off` case (remove instead of disable buttons)
  - [x] ~~iphone gridview~~
  - [ ] ipad sidebar 
- [ ] find out what to do about email/link tracking and notifications

## not implemented in mobile yet
- [ ] `chatter_attachment_preference`
- [ ] `followup_reminder`
- [ ] `send_later`
- [ ] `signature extraction`

# Reference
https://basecamp.com/2080489/projects/5982827/messages/42421705

https://docs.google.com/a/cirruspath.com/spreadsheets/d/1Zr4n3X1Aw-gq7Iv8ICj1mREyo6E6onF0-w2MF2BxckQ/edit?usp=sharing_eid

https://cirruspath.atlassian.net/browse/IOS-318 
https://portal.isdev.info:8443/jira/browse/IPADCIRRUS-1346

`CPDataManager`
`updateOrCreateSingleObjectByClass`

https://free.dev.cirrusinsight.com/sfdcLogin.php 
https://free.dev.cirrusinsight.com/services/plan

https://secure3.cirrusinsight.com/services/plan

# Done  
- [x] ipad should turn off badges https://github.com/cirruspath/Cirrus-Insight-Mobile-iOS/pull/360
- [x] merge update https://github.com/cirruspath/Cirrus-Insight-Mobile-iOS/pull/339
- [x] resolve https://portal.isdev.info:8443/jira/browse/IPADCIRRUS-1346
- [x] create a dev settings controller for qa
- [x] write instructions for qa https://portal.isdev.info:8443/jira/browse/IPADCIRRUS-1346
- [x] ~~prevent gridview dismiss when upselling~~ gridview was removed with contact view update https://github.com/cirruspath/Cirrus-Insight-Mobile-iOS/pull/308
- [x] delete `wip*` branches after merge https://github.com/dkhamsing/Cirrus-Insight-Mobile-iOS/commits/dev/permissions https://github.com/cirruspath/Cirrus-Insight-Mobile-iOS/pull/326
- integrate contact pills
  - [x] ipad tap on contact not in salesforce, should do nothing (right now opens sidepanel)
  - [x] fix email contact vc
  - [x] fix salesforce contact vc
