### ISSUE TITLE
Link tracking notifications

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/work#4]
https://github.com/cirruspath/Cirrus-Insight-Mobile-iOS/pull/398

# test
- [x] app on production
- [x] rc app

# misc

- [x] check for bundle app version to register token

# node

- [x] requires change on service for `ios`

https://github.com/dccirrus/Cirrus-Insight-Mobile/blob/feature/CI-656/node/server.js 

condition
- `device.app_version` => `1.4.1`
- or contains `RC`

`sendIosPush(message, device)` should now take `data`: `sendIosPush(message, data, device)`

type corresponds to `data.type`
- type = `email_open`
- type = `link_open` 

depending on `type`
- message = `subject`\n`daniel` opened this email at `5/28/2015`, `2:25:02 PM`
- message = `subject`\n`daniel` clicked on "`google.com`" at `5/28/2015`, `2:25:02 PM`

update notification params
``` 
notification.alert = message

notification.payload {
  mid = messageid
  type = data.type
}
```

# reference

- https://cirruspath.atlassian.net/browse/IOS-294
- https://portal.isdev.info:8443/jira/browse/IPADCIRRUS-1438
- will be up on `free.dev.cirrusinsight.com`

notification payload

```
{
    aps =     {
        alert = "subject\ndaniel opened this email at 5/28/2015, 2:23:22 PM"
    };
    mid = 146b010bc5a0a703;
    type = "email_open";
}

```
 

```
Remote Notifications:

Type:
Link_1 - Link Tracking
Email_Open - Email Open
Follow-Up Reminders 
Marketing -
Real-Time Email - (Gmail API)
```

**Comment by dkhamsing** [comment]
cirruspath/Cirrus-Insight-Mobile-iOS#398
