### ISSUE TITLE
Assistant.to  

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/work#7]
# TODO
- [ ] tutorial assets
- [ ] description field in api
- [ ] ci landing pages
- [ ] ci emails
- [ ] test on production
- [x] handle revoked token

# bugs
- [ ] :exclamation: sept 9 launch, aug 31 submit for review
- [ ] Snap scroll view when scrolling horizontal
- [ ] handle when meeting straddles / spans two days
- [ ] update implementation to show at most two overlapping events: example, stack 5 events at the same time.. use minimum width?
- [ ] import a large caelndar / profile performance 
- [ ] uitextview placeholder visual bug
- [ ] visual bug when selecting time over existing staggered meetings.. see image

![visual-bug](https://cloud.githubusercontent.com/assets/4723115/9231606/f248b870-40dd-11e5-9654-14b829ee7a2e.png)

# need clarification
- [ ] ui what happens when we reach the edge
- [x] canceling/resetting ato
- [x] apply timeslots to existing meetings when updating from picker
- [x] is ci returning a permission for assistant.to, what is the permission name?
- [x] show more (5) days on ipad?

# api
- [x] generate html to paste into email
- [x] vincent: get google access token from ci 
- https://docs.google.com/document/d/1cWw9xZvfzHAHnebIzBFUDjrCl-4ub2rBV8PkucfEXNU/edit
- [x] config route
  - https://test.cirrusinsight.com/services/assistantto/config
  - https://a2.dev.cirrusinsight.com/api/config
- [x] verify what happens when clicking works for me or doesnt work for me in email
- [x] new html template with inline css style, options for preview only
- [ ] max number of days to come back from api config
- [ ] support for description field
- [ ] more flexible in formats (json)

# reference
- https://github.com/nghialv/Sapporo
- https://docs.google.com/document/d/1d52EXeYQ85f7Vfkw1_dYPsmilP9AF2wK-L8m-8OPu3o/edit
- https://basecamp.com/2080489/projects/8447257/todos/186181059 .. last rev reviewed `v2`
- https://cirruspath.atlassian.net/browse/IOS-451
- https://www.assistant.to/

# design 
- [x] visual design holla
- 1x, 2x, 3x
- [x] assistant-enabled
- [x] assistant-disabled
- [x] assistant-logo-toolbar
- [x] how picking available times ui work, especially blocking days (can only select 3 days)

# archive
- [x] scrollview
- [x] scroll to current time with offset: REDUCE offset
- [x] offset improper as you scroll down
- [x] prevent selecting time slot in past
- [x] prevent input until existing meetings have been populated
- [x] service: cache response
- [x] cleanup pickers data source
- [x] set initial timezone value async
- [x] go back to ato after selected times: repopulate selected meetings
- [x] reset availability 
- [x] finish building out grid lines
- [x] update ui when switching timezone
- [x] check for authentication (server has access token)
- [x] restrict toolbar to gmail
- [x] remove assistant button when not gmail
- [x] over time bottom and top offset scrolling horizontally get mismatched
- [x] handle when the js div cannot be found
- [x] ios8 picker does not work in simulator :cry: 
- [x] switch timezone, then select meetings (they are offset with timezone)
- [x] ^ hit save, select meetings
- [x] overlap own selection.. should update the button start and end
- [x] return to schedule after insert.. save button is disabled
- [x] update timezone should change time label in selected buttons
- [x] changing timezone where date actually switch to next day
- [x] break up start and end time before posting to api.. confirm with alex
- [x] add black line to current time down to minute
- [x] add separators to large block of meetings to split according to time slots
- [x] when updating timezone, overlapping meetings get duplicated
- [x] overlap events.. https://github.com/cirruspath/Betty-web/blob/test/app/assets/javascripts/app/controllers.js.coffee#L355
- [x] reloading does not remember meeting length
- [x] meeting data
- [x] merging
- [x] reload /redraw overlapping
- [x] change time display
- [x] handle cropping meeting view text
- [x] lock portrait 
- [x] when getting 1.5 slot, extend end time
- [x] clean up code (lots of commented out code)
- [x] location history and favorite 
- [x] do not reuse cells
- [x] memory issues - set button to nil when removed 
- [x] ios7 issues (cannot hide change constant around picker)
- [x] verify ipad 
- [x] ios 7 textview have no height
- [x] sometimes it takes two taps to be able to create availability slot on calendar
- [x] refactor to reuse spinner view
- [x] hit preview route instead of create route
- [x] inserted email template should have same size.. 
- [x] revisit scroll offset in grid controller 
- [x] scroll to next day and gray disabled view do not work when gmt goes to next day
- [x] make each row not as tall.. maybe 20px ?
- [x] bug with scroll bars after pasting `meeting html`
- [x] Errors when cannot reach out internet
- [x] get config before showing ato controller
- [x] ios7 / iphon 4s: what is with the long delay before showing controller
- [x] show message about fetching availability
- [x] ios7 render preview
- [x] fix hour offset for existing event
- [x] match hours in ui
- [x] ato floating button is missing when switching between gmail and yahoo (this feature is gmail only)
- [x] rebase
- [x] uitextview wrapping issue
- [x] scroll to current time broken when going to next day after changing time zone
- [x] verify time changing after 5pm
- [x] adjust scrollview in will appear??
- [x] overlapping does not work after changing timezone :cry: 
- [x] logging to amplitude

**Comment by dkhamsing** [comment]
Merged https://github.com/cirruspath/Cirrus-Insight-Mobile-iOS/pull/442
